name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build -t demo/vue3-reactive-app:${{  github.ref_name }} .

    - name: Tag the image
      run: |
        docker tag demo/vue3-reactive-app:${{  github.ref_name }} vgzsysadm/vue3-reactive-app:latest

    - name: Push the Docker image to Docker Hub latest
      run: docker push vgzsysadm/vue3-reactive-app:latest
